---
kind: pipeline
type: docker
name: test

trigger:
  event:
    - push
    - custom

steps:
  - name: lint
    image: python:3
    commands:
      - ./setup.sh
      - just install-venv
      - just lint
