---

services:
  jellyfin-vue:
    image: jellyfin/jellyfin-vue:unstable
    container_name: jellyfin-vue
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
    restart: always
    ports:
      - 8084:80
    environment:
      DEFAULT_SERVERS: "https://watch.${TESSERACT_DOMAIN}"
