---

services:
  languagetool:
    build:
      context: ../dockerfiles
      dockerfile: Dockerfile.languagetool
      args:
        NGRAMS_FILE: "ngrams-en-20150817.zip"
    container_name: languagetool
    ports:
      - 8010:8010
    environment:
      - Java_Xms=512m
      - Java_Xmx=1g
