---

services:
  karakeep:
    image: ghcr.io/karakeep-app/karakeep:release
    container_name: karakeep
    restart: always
    ports:
      - 3000:3000
    environment:
      DATA_DIR: /data
      MAX_ASSET_SIZE_MB: 50
      DB_WAL_MODE: true
      NEXTAUTH_SECRET: "${TESSERACT_KARAKEEP_SECRET}"
      NEXTAUTH_URL: "http://charizard.${TESSERACT_DOMAIN}:3000"
      MEILI_ADDR: http://karakeep-meilisearch:7700
      MEILI_MASTER_KEY: "${TESSERACT_KARAKEEP_SECRET}"
      BROWSER_WEB_URL: http://karakeep-chrome:9222
      CRAWLER_NUM_WORKERS: 2
      CRAWLER_FULL_PAGE_SCREENSHOT: true
      CRAWLER_FULL_PAGE_ARCHIVE: true
      OPENAI_BASE_URL: "https://ai.${TESSERACT_DOMAIN}"
      OPENAI_API_KEY: "notrequired"
      INFERENCE_TEXT_MODEL: balanced
      INFERENCE_IMAGE_MODEL: balanced
      INFERENCE_JOB_TIMEOUT_SEC: 120
      INFERENCE_CONTEXT_LENGTH: 32768
      INFERENCE_USE_MAX_COMPLETION_TOKENS: true
      INFERENCE_ENABLE_AUTO_TAGGING: true
      INFERENCE_ENABLE_AUTO_SUMMARIZATION: true
      EMBEDDING_ENABLE_AUTO_INDEXING: true
      SEMANTIC_SEARCH_ENABLED: true
      EMBEDDING_TEXT_MODEL: embed
      EMBEDDING_DIMENSIONS: 192
      EMBEDDING_CONTEXT_LENGTH: 2000
    volumes:
      - "${TESSERACT_APPDATA_PATH}/karakeep-data:/data"

  karakeep-meilisearch:
    image: getmeili/meilisearch:v1.41.0
    container_name: karakeep-meilisearch
    restart: always
    environment:
      MEILI_NO_ANALYTICS: true
      MEILI_MASTER_KEY: "${TESSERACT_KARAKEEP_SECRET}"
    volumes:
      - "${TESSERACT_APPDATA_PATH}/karakeep-meilisearch:/meili_data"

  karakeep-chrome:
    image: zenika/alpine-chrome:124
    container_name: karakeep-chrome
    restart: always
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
      - --disable-blink-features=AutomationControlled
      - --window-size=1440,900
